file 'config/initializers/secret_token.rb' do
  path = Rails.root + 'config' + 'initializers' + 'secret_token.rb'
  secret = SecureRandom.hex(64)
  path.open('w') do |io|
    io.write <<-TEXT
# This file was generated by 'rake generate_secret_token', and should
# not be made visible to public.

# Be sure to restart your server when you modify this file.

# Your secret key for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.

BuckyBox::Application.config.secret_token = '#{secret}'
    TEXT
  end
end

desc 'Generates a secret token for the application'
task :generate_secret_token => ['config/initializers/secret_token.rb']
