module OrdersHelper
  def order_customisation(order)
    description = order.customisation_description
    content_tag(:span, truncate(description), title: description)
  end

  def order_extras(order)
    description = order.extras_description(true)
    content_tag(:span, truncate(description), title: description)
  end

  def order_frequencies
    ScheduleRule::RECUR.map { |frequencies| [frequencies.to_s.titleize, frequencies.to_s] }
  end

  def order_schedule(order)
    if order.recurs?
      order.schedule_rule.to_s
    elsif order.next_occurrence
      "Deliver on #{order.next_occurrence.strftime("%A")}"
    else
      "No future delivery scheduled"
    end
  end

  # Show the orders next delivery dates, link to the delivery screen if it is within the forcast range
  def orders_next_deliveries(order, options = {})
    options = { with_link: true }.merge(options)

    order_occurrences = order.next_occurrences(5, Date.current).map do |day|
      formatted_day = day.to_s(:flux_cap)

      if options[:with_link] && day <= Order::FORCAST_RANGE_FORWARD.from_now.to_date
        link_to(formatted_day, date_distributor_deliveries_path(day, order.delivery_service))
      else
        formatted_day
      end
    end

    unless order_occurrences.empty?
      order_occurrences.join(', ').html_safe
    end
  end

  def order_pause_date_formatted(order)
    date = order.pause_date
    return date ? date.to_s(:pause) : ''
  end

  def order_resume_date_formatted(order)
    date = order.resume_date
    return date ? date.to_s(:pause) : ''
  end

  def all_order_start_dates(distributor, count = 14)
    next_occurrences = distributor.delivery_services.inject([]) { |a,r| a += order_start_dates(r, count); a }
    return next_occurrences.uniq.sort{ |a,b| a[1] <=> b[1] }
  end

  def order_delete_warning(order)
    no_deliveries_confirm = "Are you sure you would like to deactivate this order? It will no longer generate deliveries."
    deliveries_confirm = "WARNING\r\rSorry some deliveries generated by this order could not be deleted as they are already for packing and delivery."

    return order.has_yellow_deliveries? ? deliveries_confirm : no_deliveries_confirm
  end
end
