#!/bin/bash -eu

export CI=1
export RAILS_ENV=test
export COVERAGE=1
export SPEC_OPTS="--format p"

cp -n config/database.yml.example config/database.yml

bundle install

bundle exec bundle-audit update
bundle exec bundle-audit check

bundle exec rake generate_secret_token
bundle exec rake db:drop db:create db:structure:load

bundle exec rubocop --rails --display-cop-names
$(dirname $0)/check_i18n
bundle exec rake

bundle exec discover-unused-partials || true
bundle exec brakeman -qz --no-progress -w3 || true # FIXME
bundle exec cane --no-doc --style-measure 160 --abc-max 30 || true # FIXME

