#!/bin/bash -eu

export CI=1
export RAILS_ENV=test
# export COVERAGE=1 # doesn't fail on non-zero exit since Ruby 2.1??
export SPEC_OPTS="--format p"

cp config/database.yml.example config/database.yml

bundle exec bundle-audit update
bundle exec bundle-audit check

bundle exec rake generate_secret_token
bundle exec rake db:drop db:create db:structure:load

bundle exec rake

bundle exec discover-unused-partials
bundle exec brakeman -qz --no-progress -w3 || true # FIXME
bundle exec cane --no-doc --style-measure 160 --abc-max 30 || true # FIXME

