#!/bin/bash -ex

export CI=1
export RAILS_ENV=test
export COVERAGE=1

[ "$1" = "--fast" ] && FAST="1"

cp -n config/application.yml{.example,}
cp -n config/database.yml{.example,}

[ -z "$FAST" ] && {
  export SPEC_OPTS="--format p"

  output="$(git submodule update --remote)"
  echo -n "$output"
  test -z "$output"

  bundle exec bundle-audit check --update

  $(dirname $0)/check_i18n

  bundle exec brakeman -qz --no-progress --no-pager -w3 || true # FIXME
  bundle exec cane --no-doc --style-measure 160 --abc-max 30 || true # FIXME

  bundle exec rake generate_secret_token
}

bundle exec rake db:drop db:create db:structure:load
bundle exec rspec
bundle exec cucumber
