require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Distributor::BanksController do

  # This should return the minimal set of attributes required to create a valid
  # Distributor::Bank. As you add validations to Distributor::Bank, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all distributor_banks as @distributor_banks" do
      bank = Distributor::Bank.create! valid_attributes
      get :index
      assigns(:distributor_banks).should eq([bank])
    end
  end

  describe "GET show" do
    it "assigns the requested bank as @bank" do
      bank = Distributor::Bank.create! valid_attributes
      get :show, :id => bank.id
      assigns(:bank).should eq(bank)
    end
  end

  describe "GET new" do
    it "assigns a new bank as @bank" do
      get :new
      assigns(:bank).should be_a_new(Distributor::Bank)
    end
  end

  describe "GET edit" do
    it "assigns the requested bank as @bank" do
      bank = Distributor::Bank.create! valid_attributes
      get :edit, :id => bank.id
      assigns(:bank).should eq(bank)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Distributor::Bank" do
        expect {
          post :create, :bank => valid_attributes
        }.to change(Distributor::Bank, :count).by(1)
      end

      it "assigns a newly created bank as @bank" do
        post :create, :bank => valid_attributes
        assigns(:bank).should be_a(Distributor::Bank)
        assigns(:bank).should be_persisted
      end

      it "redirects to the created bank" do
        post :create, :bank => valid_attributes
        response.should redirect_to(Distributor::Bank.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bank as @bank" do
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Bank.any_instance.stub(:save).and_return(false)
        post :create, :bank => {}
        assigns(:bank).should be_a_new(Distributor::Bank)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Bank.any_instance.stub(:save).and_return(false)
        post :create, :bank => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bank" do
        bank = Distributor::Bank.create! valid_attributes
        # Assuming there are no other distributor_banks in the database, this
        # specifies that the Distributor::Bank created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Distributor::Bank.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => bank.id, :bank => {'these' => 'params'}
      end

      it "assigns the requested bank as @bank" do
        bank = Distributor::Bank.create! valid_attributes
        put :update, :id => bank.id, :bank => valid_attributes
        assigns(:bank).should eq(bank)
      end

      it "redirects to the bank" do
        bank = Distributor::Bank.create! valid_attributes
        put :update, :id => bank.id, :bank => valid_attributes
        response.should redirect_to(bank)
      end
    end

    describe "with invalid params" do
      it "assigns the bank as @bank" do
        bank = Distributor::Bank.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Bank.any_instance.stub(:save).and_return(false)
        put :update, :id => bank.id, :bank => {}
        assigns(:bank).should eq(bank)
      end

      it "re-renders the 'edit' template" do
        bank = Distributor::Bank.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Bank.any_instance.stub(:save).and_return(false)
        put :update, :id => bank.id, :bank => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bank" do
      bank = Distributor::Bank.create! valid_attributes
      expect {
        delete :destroy, :id => bank.id
      }.to change(Distributor::Bank, :count).by(-1)
    end

    it "redirects to the distributor_banks list" do
      bank = Distributor::Bank.create! valid_attributes
      delete :destroy, :id => bank.id
      response.should redirect_to(distributor_banks_url)
    end
  end

end
