require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Distributor::BoxesController do

  # This should return the minimal set of attributes required to create a valid
  # Distributor::Box. As you add validations to Distributor::Box, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all distributor_boxes as @distributor_boxes" do
      box = Distributor::Box.create! valid_attributes
      get :index
      assigns(:distributor_boxes).should eq([box])
    end
  end

  describe "GET show" do
    it "assigns the requested box as @box" do
      box = Distributor::Box.create! valid_attributes
      get :show, :id => box.id
      assigns(:box).should eq(box)
    end
  end

  describe "GET new" do
    it "assigns a new box as @box" do
      get :new
      assigns(:box).should be_a_new(Distributor::Box)
    end
  end

  describe "GET edit" do
    it "assigns the requested box as @box" do
      box = Distributor::Box.create! valid_attributes
      get :edit, :id => box.id
      assigns(:box).should eq(box)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Distributor::Box" do
        expect {
          post :create, :box => valid_attributes
        }.to change(Distributor::Box, :count).by(1)
      end

      it "assigns a newly created box as @box" do
        post :create, :box => valid_attributes
        assigns(:box).should be_a(Distributor::Box)
        assigns(:box).should be_persisted
      end

      it "redirects to the created box" do
        post :create, :box => valid_attributes
        response.should redirect_to(Distributor::Box.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved box as @box" do
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Box.any_instance.stub(:save).and_return(false)
        post :create, :box => {}
        assigns(:box).should be_a_new(Distributor::Box)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Box.any_instance.stub(:save).and_return(false)
        post :create, :box => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested box" do
        box = Distributor::Box.create! valid_attributes
        # Assuming there are no other distributor_boxes in the database, this
        # specifies that the Distributor::Box created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Distributor::Box.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => box.id, :box => {'these' => 'params'}
      end

      it "assigns the requested box as @box" do
        box = Distributor::Box.create! valid_attributes
        put :update, :id => box.id, :box => valid_attributes
        assigns(:box).should eq(box)
      end

      it "redirects to the box" do
        box = Distributor::Box.create! valid_attributes
        put :update, :id => box.id, :box => valid_attributes
        response.should redirect_to(box)
      end
    end

    describe "with invalid params" do
      it "assigns the box as @box" do
        box = Distributor::Box.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Box.any_instance.stub(:save).and_return(false)
        put :update, :id => box.id, :box => {}
        assigns(:box).should eq(box)
      end

      it "re-renders the 'edit' template" do
        box = Distributor::Box.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Box.any_instance.stub(:save).and_return(false)
        put :update, :id => box.id, :box => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested box" do
      box = Distributor::Box.create! valid_attributes
      expect {
        delete :destroy, :id => box.id
      }.to change(Distributor::Box, :count).by(-1)
    end

    it "redirects to the distributor_boxes list" do
      box = Distributor::Box.create! valid_attributes
      delete :destroy, :id => box.id
      response.should redirect_to(distributor_boxes_url)
    end
  end

end
