require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Distributor::InvoiceInformationController do

  # This should return the minimal set of attributes required to create a valid
  # Distributor::InvoiceInformation. As you add validations to Distributor::InvoiceInformation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all distributor_invoice_information as @distributor_invoice_information" do
      invoice_information = Distributor::InvoiceInformation.create! valid_attributes
      get :index
      assigns(:distributor_invoice_information).should eq([invoice_information])
    end
  end

  describe "GET show" do
    it "assigns the requested invoice_information as @invoice_information" do
      invoice_information = Distributor::InvoiceInformation.create! valid_attributes
      get :show, :id => invoice_information.id
      assigns(:invoice_information).should eq(invoice_information)
    end
  end

  describe "GET new" do
    it "assigns a new invoice_information as @invoice_information" do
      get :new
      assigns(:invoice_information).should be_a_new(Distributor::InvoiceInformation)
    end
  end

  describe "GET edit" do
    it "assigns the requested invoice_information as @invoice_information" do
      invoice_information = Distributor::InvoiceInformation.create! valid_attributes
      get :edit, :id => invoice_information.id
      assigns(:invoice_information).should eq(invoice_information)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Distributor::InvoiceInformation" do
        expect {
          post :create, :invoice_information => valid_attributes
        }.to change(Distributor::InvoiceInformation, :count).by(1)
      end

      it "assigns a newly created invoice_information as @invoice_information" do
        post :create, :invoice_information => valid_attributes
        assigns(:invoice_information).should be_a(Distributor::InvoiceInformation)
        assigns(:invoice_information).should be_persisted
      end

      it "redirects to the created invoice_information" do
        post :create, :invoice_information => valid_attributes
        response.should redirect_to(Distributor::InvoiceInformation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved invoice_information as @invoice_information" do
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::InvoiceInformation.any_instance.stub(:save).and_return(false)
        post :create, :invoice_information => {}
        assigns(:invoice_information).should be_a_new(Distributor::InvoiceInformation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::InvoiceInformation.any_instance.stub(:save).and_return(false)
        post :create, :invoice_information => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested invoice_information" do
        invoice_information = Distributor::InvoiceInformation.create! valid_attributes
        # Assuming there are no other distributor_invoice_information in the database, this
        # specifies that the Distributor::InvoiceInformation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Distributor::InvoiceInformation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => invoice_information.id, :invoice_information => {'these' => 'params'}
      end

      it "assigns the requested invoice_information as @invoice_information" do
        invoice_information = Distributor::InvoiceInformation.create! valid_attributes
        put :update, :id => invoice_information.id, :invoice_information => valid_attributes
        assigns(:invoice_information).should eq(invoice_information)
      end

      it "redirects to the invoice_information" do
        invoice_information = Distributor::InvoiceInformation.create! valid_attributes
        put :update, :id => invoice_information.id, :invoice_information => valid_attributes
        response.should redirect_to(invoice_information)
      end
    end

    describe "with invalid params" do
      it "assigns the invoice_information as @invoice_information" do
        invoice_information = Distributor::InvoiceInformation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::InvoiceInformation.any_instance.stub(:save).and_return(false)
        put :update, :id => invoice_information.id, :invoice_information => {}
        assigns(:invoice_information).should eq(invoice_information)
      end

      it "re-renders the 'edit' template" do
        invoice_information = Distributor::InvoiceInformation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::InvoiceInformation.any_instance.stub(:save).and_return(false)
        put :update, :id => invoice_information.id, :invoice_information => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested invoice_information" do
      invoice_information = Distributor::InvoiceInformation.create! valid_attributes
      expect {
        delete :destroy, :id => invoice_information.id
      }.to change(Distributor::InvoiceInformation, :count).by(-1)
    end

    it "redirects to the distributor_invoice_information list" do
      invoice_information = Distributor::InvoiceInformation.create! valid_attributes
      delete :destroy, :id => invoice_information.id
      response.should redirect_to(distributor_invoice_information_index_url)
    end
  end

end
