require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Distributor::PaymentsController do

  # This should return the minimal set of attributes required to create a valid
  # Distributor::Payment. As you add validations to Distributor::Payment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all distributor_payments as @distributor_payments" do
      payment = Distributor::Payment.create! valid_attributes
      get :index
      assigns(:distributor_payments).should eq([payment])
    end
  end

  describe "GET show" do
    it "assigns the requested payment as @payment" do
      payment = Distributor::Payment.create! valid_attributes
      get :show, :id => payment.id
      assigns(:payment).should eq(payment)
    end
  end

  describe "GET new" do
    it "assigns a new payment as @payment" do
      get :new
      assigns(:payment).should be_a_new(Distributor::Payment)
    end
  end

  describe "GET edit" do
    it "assigns the requested payment as @payment" do
      payment = Distributor::Payment.create! valid_attributes
      get :edit, :id => payment.id
      assigns(:payment).should eq(payment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Distributor::Payment" do
        expect {
          post :create, :payment => valid_attributes
        }.to change(Distributor::Payment, :count).by(1)
      end

      it "assigns a newly created payment as @payment" do
        post :create, :payment => valid_attributes
        assigns(:payment).should be_a(Distributor::Payment)
        assigns(:payment).should be_persisted
      end

      it "redirects to the created payment" do
        post :create, :payment => valid_attributes
        response.should redirect_to(Distributor::Payment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved payment as @payment" do
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Payment.any_instance.stub(:save).and_return(false)
        post :create, :payment => {}
        assigns(:payment).should be_a_new(Distributor::Payment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Payment.any_instance.stub(:save).and_return(false)
        post :create, :payment => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested payment" do
        payment = Distributor::Payment.create! valid_attributes
        # Assuming there are no other distributor_payments in the database, this
        # specifies that the Distributor::Payment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Distributor::Payment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => payment.id, :payment => {'these' => 'params'}
      end

      it "assigns the requested payment as @payment" do
        payment = Distributor::Payment.create! valid_attributes
        put :update, :id => payment.id, :payment => valid_attributes
        assigns(:payment).should eq(payment)
      end

      it "redirects to the payment" do
        payment = Distributor::Payment.create! valid_attributes
        put :update, :id => payment.id, :payment => valid_attributes
        response.should redirect_to(payment)
      end
    end

    describe "with invalid params" do
      it "assigns the payment as @payment" do
        payment = Distributor::Payment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Payment.any_instance.stub(:save).and_return(false)
        put :update, :id => payment.id, :payment => {}
        assigns(:payment).should eq(payment)
      end

      it "re-renders the 'edit' template" do
        payment = Distributor::Payment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Payment.any_instance.stub(:save).and_return(false)
        put :update, :id => payment.id, :payment => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested payment" do
      payment = Distributor::Payment.create! valid_attributes
      expect {
        delete :destroy, :id => payment.id
      }.to change(Distributor::Payment, :count).by(-1)
    end

    it "redirects to the distributor_payments list" do
      payment = Distributor::Payment.create! valid_attributes
      delete :destroy, :id => payment.id
      response.should redirect_to(distributor_payments_url)
    end
  end

end
