require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Distributor::TransactionsController do

  # This should return the minimal set of attributes required to create a valid
  # Distributor::Transaction. As you add validations to Distributor::Transaction, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all distributor_transactions as @distributor_transactions" do
      transaction = Distributor::Transaction.create! valid_attributes
      get :index
      assigns(:distributor_transactions).should eq([transaction])
    end
  end

  describe "GET show" do
    it "assigns the requested transaction as @transaction" do
      transaction = Distributor::Transaction.create! valid_attributes
      get :show, :id => transaction.id
      assigns(:transaction).should eq(transaction)
    end
  end

  describe "GET new" do
    it "assigns a new transaction as @transaction" do
      get :new
      assigns(:transaction).should be_a_new(Distributor::Transaction)
    end
  end

  describe "GET edit" do
    it "assigns the requested transaction as @transaction" do
      transaction = Distributor::Transaction.create! valid_attributes
      get :edit, :id => transaction.id
      assigns(:transaction).should eq(transaction)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Distributor::Transaction" do
        expect {
          post :create, :transaction => valid_attributes
        }.to change(Distributor::Transaction, :count).by(1)
      end

      it "assigns a newly created transaction as @transaction" do
        post :create, :transaction => valid_attributes
        assigns(:transaction).should be_a(Distributor::Transaction)
        assigns(:transaction).should be_persisted
      end

      it "redirects to the created transaction" do
        post :create, :transaction => valid_attributes
        response.should redirect_to(Distributor::Transaction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transaction as @transaction" do
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Transaction.any_instance.stub(:save).and_return(false)
        post :create, :transaction => {}
        assigns(:transaction).should be_a_new(Distributor::Transaction)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Transaction.any_instance.stub(:save).and_return(false)
        post :create, :transaction => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transaction" do
        transaction = Distributor::Transaction.create! valid_attributes
        # Assuming there are no other distributor_transactions in the database, this
        # specifies that the Distributor::Transaction created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Distributor::Transaction.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => transaction.id, :transaction => {'these' => 'params'}
      end

      it "assigns the requested transaction as @transaction" do
        transaction = Distributor::Transaction.create! valid_attributes
        put :update, :id => transaction.id, :transaction => valid_attributes
        assigns(:transaction).should eq(transaction)
      end

      it "redirects to the transaction" do
        transaction = Distributor::Transaction.create! valid_attributes
        put :update, :id => transaction.id, :transaction => valid_attributes
        response.should redirect_to(transaction)
      end
    end

    describe "with invalid params" do
      it "assigns the transaction as @transaction" do
        transaction = Distributor::Transaction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Transaction.any_instance.stub(:save).and_return(false)
        put :update, :id => transaction.id, :transaction => {}
        assigns(:transaction).should eq(transaction)
      end

      it "re-renders the 'edit' template" do
        transaction = Distributor::Transaction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Distributor::Transaction.any_instance.stub(:save).and_return(false)
        put :update, :id => transaction.id, :transaction => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transaction" do
      transaction = Distributor::Transaction.create! valid_attributes
      expect {
        delete :destroy, :id => transaction.id
      }.to change(Distributor::Transaction, :count).by(-1)
    end

    it "redirects to the distributor_transactions list" do
      transaction = Distributor::Transaction.create! valid_attributes
      delete :destroy, :id => transaction.id
      response.should redirect_to(distributor_transactions_url)
    end
  end

end
